[build]
  # Nếu bạn đã cấu hình Base directory trong Netlify là "FrontEnd" thì để trống dòng này
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200